on: [push, repository_dispatch]

jobs:
  gem-install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['2.5.x', '2.6.x']

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby ${{ matrix.ruby-version }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Show gem version
        run: gem -v

      - name: Add ~/.gemrc
        run: |
          cat > ~/.gemrc << EOM
          ---
          :backtrace: false
          :bulk_threshold: 1000
          :sources:
          - https://rubygems.org/
          - https://token:${{ secrets.GITHUB_TOKEN }}@rubygems.pkg.github.com/github-packages-examples/
          :update_sources: true
          :verbose: true  
          EOM

      - name: Install Gem
        run: gem install rubygems-publish

      - name: Add main.rb
        run: |
          cat > main.rb << EOM
          require 'rubygems-publish'
          RubyGemsPublish.hello
          EOM

      - name: Run using ruby
        run: ruby main.rb
